version: '3.8'
services:
  ytpld:
    image: git.darkzoul.org/dark_zoul/ytpld:latest
    container_name: ytpld
    restart: no
    volumes:
      - /path/to/downloads:/app/downloads
      - /path/to/config:/app/config
