# Build and push Docker image to Gitea container registry
name: Build Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: git.darkzoul.org
      REGISTRY_OWNER: dark_zoul
      IMAGE_NAME: youtube-playlist-downloader
    steps:
      - name: Checkout code
        uses: https://gitea.com/actions/checkout@v5

      - name: Extract tag name
        run: |
          REF="${GITEA_REF:-$GITHUB_REF}"
          TAG="${REF#refs/tags/}"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker image with release tag
        run: docker build ./ -t ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Tag Docker image as latest
        run: docker tag ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_OWNER }}/${{ env.IMAGE_NAME }}:latest
      
      - name: Upload image artifact
        uses: christopherhx/gitea-upload-artifact@v4
        with:
          name: docker-image
          path: ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Login to the Container registry
        uses: https://gitea.com/docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_OWNER }}
          password: ${{ secrets.MY_REGISTRY_ACCESS_TOKEN }}
          
      - name: Push Docker image with release tag
        run: docker push ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Push Docker image as latest
        run: docker push ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_OWNER }}/${{ env.IMAGE_NAME }}:latest
