# Build and push Docker image to Gitea container registry
name: Build Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: git.darkzoul.org
      OWNER: darkzoul
      IMAGE_NAME: youtube-playlist-downloader
    steps:
      - name: Checkout code
        uses: https://gitea.com/actions/checkout@v5

      - name: Extract tag name
        run: |
          REF="${GITEA_REF:-$GITHUB_REF}"
          TAG="${REF#refs/tags/}"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker image with release tag
        run: docker build ./ -t ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} -t ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Tag Docker image as latest
        run: docker tag ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:latest

      - name: Login to the Container registry
        uses: https://gitea.com/docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.OWNER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          
      - name: Push Docker image with release tag
        run: docker push ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Push Docker image as latest
        run: docker push ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
  
