name: Test Gitea Variables

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  print-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Print all available Gitea variables
        run: |
          echo "ref_name: ${{ gitea.ref_name }}"
          echo "ref: ${{ gitea.ref }}"
          echo "repository: ${{ gitea.repository }}"
          echo "event_name: ${{ gitea.event_name }}"
          echo "sha: ${{ gitea.sha }}"
          echo "workflow: ${{ gitea.workflow }}"
