name: Lint Python code

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Ruff
        run: pip install ruff

      - name: Run linter
        run: ruff check .